# Spring 2024: CS5720 
## Neural Networks & Deep Learning - ICP-3

In [13]:
# importing necessary libraries for the assignment
import numpy as np

#### 1.Create a class Employee and then do the following
    - • Create a data member to count the number of Employees
    - • Create a constructor to initialize name, family, salary, department
    - • Create a function to average salary
    - • Create a Fulltime Employee class and it should inherit the properties of Employee class
    - • Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [17]:
# created class Employee
class Employee():
    # create data members to keep count of employee count and list of salaries
    emp_count = 0
    
    # constructor to initilize the variables
    def __init__(self,name:str,family:str,salary:float,department:str):
        self.name = name,
        self.family = family,
        self.salary = salary,
        self.department = department,
        Employee.emp_count += 1
    
    # funtion to return average of salary
    def avg_salary(employees:list):
        # calculate salaries average
        salaries_list = [emp.salary[0] for emp in employees]
        # avg_sal = sum(salaries_list)/Employee.emp_count     # method 1
        avg_sal = np.mean(salaries_list)                      # method 2
        return avg_sal
    
# created FullTimeEmployee class and inherit the properties from Employee class
class FullTimeEmployee(Employee):
    def __init__(self,name:str,family:int,salary:float,department:str):
        # calling parent class constructor
        super().__init__(name,family,salary,department) 

employees = []
employees.append(Employee("Vamsi","Katam",240000,"analytics"))
employees.append(Employee("Krishna","Katam",540000,"CTO"))

employees.append(FullTimeEmployee("vamsi krishna","Katam",320000,"data science"))
employees.append(FullTimeEmployee("Sai","Katam",530000,"data analytics"))


print("using employee class",Employee.avg_salary(employees))
print("using fulltime employee class",FullTimeEmployee.avg_salary(employees))

using employee class 407500.0
using fulltime employee class 407500.0


#### 2. Using NumPy create random vector of size 20 having only float in the range 1-20. 
    -Then reshape the array to 4 by 5
    -Then replace the max in each row by 0 (axis=1)
(you can NOT implement it via for loop)

In [26]:
arr = np.random.uniform(1,20,20) # created a random vector of size 20 in the range of 1 - 20.
arr = arr.reshape(4,5) # reshaped the vector to array of (4,5) shape

In [27]:
# replace the max in each row by 0 (axis = 1)

# print array before replacement
print("array before :\n\n",arr,end="\n\n\n")

# get max elements of each row and reshape it 
row_wise_max = np.max(arr,axis = 1).reshape(-1,1)

arr[arr == row_wise_max] = 1

# print array after replacement
print("array after replace the max element of each row with 1: \n\n", arr)

array before :

 [[15.69529342 18.36578353  4.00532966 17.17711657 12.98965824]
 [ 2.30651039 10.19354277 18.11672849 15.36012699 19.85540985]
 [17.76612006  5.15978104  7.32213796  6.69592947 15.49906417]
 [ 9.78627137  4.58787784 19.09781417  6.84710696  8.9167378 ]]


array after replace the max element of each row with 1: 

 [[15.69529342  1.          4.00532966 17.17711657 12.98965824]
 [ 2.30651039 10.19354277 18.11672849 15.36012699  1.        ]
 [ 1.          5.15978104  7.32213796  6.69592947 15.49906417]
 [ 9.78627137  4.58787784  1.          6.84710696  8.9167378 ]]
