# Spring 2024: CS5720 
## Neural Networks & Deep Learning - ICP-3

#### 1Create a class Employee and then do the following
    - • Create a data member to count the number of Employees
    - • Create a constructor to initialize name, family, salary, department
    - • Create a function to average salary
    - • Create a Fulltime Employee class and it should inherit the properties of Employee class
    - • Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [160]:
# created class Employee
class Employee():
    # create data members to keep count of employee count and list of salaries
    emp_count = 0
    salaries = []
    
    # constructor to initilize the variables
    def __init__(self,name:str,family:int,salary:float,department:str):
        self.name = name,
        self.family = family,
        self.salary = salary,
        self.department = department,
        Employee.emp_count += 1
        Employee.salaries.append(salary)
    
    # funtion to return average of salary
    def avg_salary(self):
        return sum(Employee.salaries)/Employee.emp_count
    
# created FullTimeEmployee class
class FullTimeEmployee(Employee):
    pass

emp1 = Employee("Vamsi",4,240000,"analytics")
emp2 = Employee("Krishna",3,540000,"CTO")

ful_emp1 = FullTimeEmployee("vamsi krishna",5,320000,"data science")
ful_emp2 = FullTimeEmployee("Sai",2,530000,"data analytics")

print("using employee class",emp1.avg_salary())
print("using fulltime employee class",ful_emp1.avg_salary())

using employee class 407500.0
using fulltime employee class 407500.0


#### 2. Using NumPy create random vector of size 20 having only float in the range 1-20. 
    -Then reshape the array to 4 by 5
    -Then replace the max in each row by 0 (axis=1)
(you can NOT implement it via for loop)

In [132]:
import numpy as np

In [143]:
arr = np.random.uniform(1,20,20) # created a random vector of size 20 in the range of 1 - 20.
arr = arr.reshape(4,5) # reshaped the vector to array of (4,5) shape

In [144]:
# replace the max in each row by 0 (axis = 1)
# print array before replacement
print("array before\n",arr,end="\n\n\n")

# get max elements of each row and reshape it 
row_wise_max = np.max(arr,axis = 1).reshape(-1,1)

arr[arr == row_wise_max] = 1

# print array after replacement
print("array before\n", arr)

array before
 [[ 8.6063413  11.76021096  8.03168441  5.63955891  7.00107046]
 [ 7.37801078 13.21503813 10.32213979  5.99171297 17.80083629]
 [18.88534946  1.84036519  4.90571023  3.00070214  7.26816271]
 [ 8.50658689 19.15507481 13.78280477  3.3352148   2.36487955]]


array before
 [[ 8.6063413   1.          8.03168441  5.63955891  7.00107046]
 [ 7.37801078 13.21503813 10.32213979  5.99171297  1.        ]
 [ 1.          1.84036519  4.90571023  3.00070214  7.26816271]
 [ 8.50658689  1.         13.78280477  3.3352148   2.36487955]]
